version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '3000:3000'
    container_name: api
    restart: always
    volumes:
      - api-logs:/usr/src/node-api/logs:rw
    environment:
      - NODE_ENV=development
    depends_on:
      - pgsql
    environment:
      DATABASE_HOST: pgsql
      DATABASE_USER: pguser
      DATABASE_PASS: pgpassword
      DATABASE_DB: nestjs
  apiHub:
    image: flaviox5/todoapi
    ports:
      - '3000:3000'
    container_name: apiHub
    restart: always
    environment:
      DATABASE_HOST: pgsql
      DATABASE_USER: pguser
      DATABASE_PASS: pgpassword
      DATABASE_DB: nestjs
    volumes:
      - api-logs:/usr/src/node-api/logs:rw
    environment:
      - NODE_ENV=development
    depends_on:
      - pgsql
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: nestjs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  api-logs:
  pg-data: